server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 853630

eureka:
  client:
    #表示是否将自己注册进Eureka Server，默认为true
    register-with-eureka: true
    #是否从Eureka Server 抓取已有的注册信息，默认为true；单节点无所谓，但集群必须设置为true，才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址
      # singleton version (单机版)
      #defaultZone: http://localhost:7001/eureka
      # cluster version (集群版)
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #服务名称修改（不要带主机名）
    instance-id: payment8001
    #访问路径有IP信息提示
    prefer-ip-address: true

    #心跳检测与持续时间
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在最后一次收到心跳后等待的时间上限，单位为秒（默认是90秒）,超时将剔除服务
    #lease-expiration-duration-in-seconds: 2




mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.sww.springcloud.entities    # 所有Entity别名类所在包